version: '3.8'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb+srv://root:root@api.wuxqj.mongodb.net/api-todo-ty?retryWrites=true&w=majority
      - JWT_SECRET=your-secret-key
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"